/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shms.with.oop;

/**
 *
 * @author rubayed
 */
public class JUabout extends javax.swing.JFrame {

    /**
     * Creates new form JUabout
     */
    public JUabout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About JU");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shms/with/oop/logo-ju.png"))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\n  Jahangirnagar University accustomed as a fully residential public university established in 1970 has now 36 departments and Six\n  Faculties along with Four institutes, with added than fifteen thousand students, and about Five hundred academics adherent to \n  teaching and research. The sprawling arresting campus is anchored 30 kilometres from the basic Dhaka, able-bodied affiliated with \n  a civic highway. The aboriginal assembly of Independent Bangladesh accepted the university its Charter in 1973 beneath which the \n  university is getting operated.\n\n  The badge of the university bears the civic annual ‘white lily’ (Lilium condidu) with three petals belted by strips of a acceptable floral \n  architecture with the name of the university in Bangla ensconcing in a semi-circle like a band of flowers.\n\n  Located at Savar abreast Dhaka, Jahangirnagar University is one of the arch Universities in Bangladesh. The University is a residential\n  one. It was formally launched on 12 January 1971 by its aboriginal adjudicator Rear Admiral S.M. Ahsan, Governor of above East \n  Pakistan. After Emergence of Bangladesh the Government allowable the Jahangirnagar University Act. 1973, which repealed the \n  antecedent authorization and renamed the University as Jahangirnagar University.The University owes its present appearance to \n  this act beneath which it is now functioning.\n\n  About: Jahangirnagar University (JU)\n  Name: Jahangirnagar University\n  Type: Public University\n  Establishment: 20th August, 1970\n  Governed By: The Jahangirnagar University Act, 1973\n  Academic Year: 1st July to 30th June\n  Postal Address: Savar, Dhaka, Bangladesh, 1342\n  Land Area: 697.56 Acre\n\n  Contact::\n  PABX: 7791045-51\n  Fax: 880-2-7791052\n  E-mail: registrar@juniv.edu\n  Website: https://juniv.edu\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUabout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUabout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUabout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUabout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JUabout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
